auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('createListing', views.createListing, name='createListing'),
    path('categoryView', views.categoryView, name='categoryView'),
   path("categoryList/<str:category_id>", views.categoryList, name='categoryList'),
   path("addWatchlist/<int:auction_id>", views.addWatchlist, name="addWatchlist"),
   path("watchlist", views.watchlist, name="watchlist"),
   path("remove_watchlist/<int:auction_id>", views.remove_watchlist, name="remove_watchlist"),
   path("indexItem/<int:auction_id>", views.indexItem, name="indexItem"),
   path('PostImage/<int:auction_id>', views.PostImage, name="PostImage")
   
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from PIL import Image
from PIL.Image import core as _imaging
from django.conf import settings
from django.conf.urls.static import static


class User(AbstractUser):
    id = models.AutoField(primary_key=True)
    pass

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=25)


    def __str__(self):
        return f"{self.category}"

class Auction(models.Model):
    id = models.AutoField(primary_key=True)

    STATUS = (
        ('Active', 'Active'),
        ('Closed', 'Closed'),
        ('Sold', 'Sold'),
    )
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()
    active = models.CharField(max_length=25, choices=STATUS)
    selectcategory = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media", blank=True)
    date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f"{self.seller}, {self.title}, {self.description}, {self.active}, {self.price}, {self.date},{self.active}, {self.image}"


class PostImage(models.Model):
    id = models.AutoField(primary_key=True)
    auction = models.ForeignKey(Auction, default=None, on_delete=models.CASCADE, related_name="postImage")
    images = models.ImageField(upload_to="media/", blank=True)

    def __str__(self):
        return self.auction.title


class Bid(models.Model):
    id = models.AutoField(primary_key=True)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_name")
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_bids")
    product_price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.buyer}, {self.product_price}, {self.date}"

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

    def __str__(self):
        return f"{self.user},  {self.comment}, {self.product_id}"

class Watchlist(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_watchlist")
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_watchlist")

    def __str__(self):
        return f"{self.user}, {self.product_id}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import *
from django.core.files.storage import FileSystemStorage
import os, os.path
import logging
from django.contrib import messages


logging.basicConfig(filename='user.log',level=logging.INFO,
    format='%(asctime)s:%(levelname)s:%(message)s')

logging.basicConfig(filename='user.log',level=logging.WARNING,
    format='%(asctime)s:%(levelname)s:%(message)s')

def index(request):
    return render(request, "auctions/index.html",{
        "auctions": Auction.objects.all(),
        "photos": PostImage.objects.all()
    })

def indexItem(request, auction_id):
    product = Auction.objects.get(pk = auction_id)
    postImage = PostImage.objects.filter(auction=auction_id)
    return render(request, "auctions/index_view.html",{
        'product': product,
        'postImage': postImage,
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            logging.info(f'{username} logged in.')
            return HttpResponseRedirect(reverse("index"))
        else:
            logging.warning(f'{username} logged in Invalid username and/or password..')
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:

            logging.warning(f'{username}-{email}typed in an incorrect password!')
            
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            logging.info(f'{username}-{email} just signed up!')
        except IntegrityError:
            logging.warning(f'{username} already taken')
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def createListing(request):
    if request.method == "POST":
        product = Auction()
        photos = PostImage()
        category = Category.objects.get(id=int(request.POST["category"]))

        product.title = request.POST["title"]
        product.seller = request.user
        product.description= request.POST["description"]
        product.active = request.POST["active"]
        product.price = request.POST["price"]
        product.image = request.FILES['image']
        product.selectcategory = category
        product.save()

        photos.auction = Auction.objects.latest('id')
        images = request.FILES.getlist('images')
        
        if images:
            for image in images:
                photos = PostImage.objects.create(images=image, auction=photos.auction)
        
        photos.save()
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/create.html",{
            "auctions":Auction.objects.all(),
            "categories": Category.objects.all(),
            "photos": PostImage.objects.all()
        })


def categoryView(request):
    return render(request,"auctions/category.html",{
        "auctions":Auction.objects.all(),
        "category": Category.objects.all(),
       
    })

def categoryList(request,category_id):
    products = Auction.objects.filter(selectcategory=category_id)
    if len(products) >= 1:
        return render(request, "auctions/category.html",{
        "auctions":Auction.objects.all(),
        "products": products
    })

    else:
        
        return redirect("categoryView")

def watchlist(request):
    product_watchlist = Watchlist.objects.all().select_related('product_id')
    if product_watchlist:
        return render(request, "auctions/watchlist.html", {
            'product_watchlist': product_watchlist
        })
    else:
        return render(request, "auctions/watchlist.html", {
            "message": "Empty"
        })

def addWatchlist(request, auction_id):
    query = Auction.objects.get(pk = auction_id)
    Watchlist.objects.create(user = request.user, product_id = query)
    return redirect(watchlist)
   
def remove_watchlist(request, auction_id):
    query = Watchlist.objects.filter(user = request.user, product_id = auction_id)
    print(query)
    if query:

        query.delete()

    return HttpResponseRedirect(reverse("watchlist"))



          


        

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{%block body%}

{% include "auctions/slider.html" %}
<h2 style='text-align:center;'>Categories</h2>


<div class="marketing container">
 
        {% for cat in category%}
            <div class="category-container">
                <div class="img-container">
                    <i class="fa fa-car" aria-hidden="true"></i>
                </div>
                <a class="text-decoration" value="{{cat.id}}" href="{% url 'categoryList' category_id=cat.id %}">{{cat}}</a>

            </div>  
            {%endfor%}
          
</div>
<hr>

 
    
<div class="container margin-bottom">
    {% for product in products%}
        <div class="row featurette">
            <div class="col-md-7">
                <li style="text-align: right;">{{product.active}}</li>
                <div >
                    <h2>{{product.title}} </h2><br>
                </div>
                
                <div>
                        Description
                    <li>{{product.description}}</li>
                </div>
                <div>
                    Seller
                    <li>{{product.seller}}</li>
                </div>

            </div>
            <div class="col-md-5">
                <img src="{{product.image.url}}" alt="" width="500" height="500"> 
            </div>
            <div>
                <a href="{% url 'addWatchlist' auction_id=product.id %}" class="btn btn-light col-2 pr-2">Add to Watchlist</a>
            </div>
        </div>

        <hr class="featurette-divider">

    {%endfor%}

</div>

{%endblock%}

auctions/templates/auctions/category_list.html
{% extends "auctions/layout.html" %}

{%block body%}

<br>

{% if message  %}

<div class="alert alert-danger">

    {{message}}

</div>

{%endif%}

{% for product in products%}

<div>       
    <h3> {{product.title}} </h3><br>
    <img src="{{product.image.url}}" alt="" width="300"> 
</div>
<div>
    <li>{{product.date}}</li>
</div>
<div>
    Description
   <li>{{product.description}}</li> 
</div>
<div>Seller
    <li>{{product.seller}}</li>
</div>

<div>Category
    <li>{{product.selectcategory}}</li>
</div>
<div>Status
    <li>{{product.active}}</li>
</div>
{%endfor%}
{%endblock%}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}



{% block body %}
{% include "auctions/slider.html" %}
<hr>
{% if message %}
<div>{{ message }}</div>
{% endif %}
<div class="container">
    <div class="margin-bottom">

        <form action="{% url 'createListing' %}" method="POST" enctype=multipart/form-data>
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="title" placeholder="Title">
            </div>
            <div class="form-group">
                <textarea class="form-control" name="description" rows="4" placeholder="Description"></textarea>
            </div>
            <div class="form-group">
                <select class="form-select" aria-label="Default select example" name="category">
                    {% for category in categories %}
                    <option value="{{category.id}}">{{category.category}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <input class="form-control" type="text" name="price" placeholder="price">
            </div>
            <div class="form-group">
                <select class="form-select" aria-label="Default select example" name="active" required=""
                    id="id_active">

                    <option selected>Active</option>

                    <option value="Active">Active</option>

                    <option value="Closed">Closed</option>

                    <option value="Sold">Sold</option>

                </select>
            </div>
            <div class="form-group">
                <input class="form-control" type="file" name="image" placeholder="Image" multiple>
                <label>Add more:</label>
                <input class="form-control" type="file" name="images" placeholder="Add more" multiple>
            </div>
            <input class="btn btn-primary" type="submit" value="Create">
        </form>
    </div>

</div>
<!-- End Jumbotron -->
{% endblock %}

auctions/templates/auctions/index-view-swiper.html
{% load static %}

<head>
    <meta charset="utf-8">
    <title>Swiper demo</title>
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="{% static 'auctions/swiper-bundle.min.css' %}">

    <!-- Demo styles -->
    <style>
        html,
        body {
            position: relative;
            height: 100%;
        }

        body {
            background: white;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #000;
            margin: 0;
            padding: 0;
        }

        .swiper-container {
            width: 50%;
            height: 50%;
        }

        .swiper-slide {
            text-align: center;
            font-size: 18px;
            background: #fff;

            /* Center slide text vertically */
            display: -webkit-box;
            display: -ms-flexbox;
            display: -webkit-flex;
            display: flex;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            -webkit-justify-content: center;
            justify-content: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            -webkit-align-items: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <!-- Swiper -->
    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for post in postImage%}
            <div class="swiper-slide"><img src="{{post.images.url}}" alt="" width="500" height="500"></div>
            {%endfor%}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>

    <!-- Swiper JS -->
    <script src="{% static '/auctions/scripts/swiper-bundle.js' %}"></script>

    <!-- Initialize Swiper -->
    <script>
        var swiper = new Swiper('.swiper-container', {
            pagination: {
                el: '.swiper-pagination',
                type: 'fraction',
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });
    </script>
</body>

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
{% include "auctions/slider.html" %}
    <div id="container">
        <div class="row">
            {% for auction in auctions %}
            {%if auction.active == "Active" %}
            <div class="col-lg-3 col-sm-6 pr-2 mb-4">
                <div class="listing">
                    <h4 class="pd-2 pr-2 pl-2 pt-2"> {{auction.title}} </h4><br>
                    <div class="center-align">
            
                        <img  src="{{auction.image.url}}" alt=""  width="300" height="250"> 
                    
                    </div>
                    
                    <div class="row"> 
                        <p class="col-6 ml-2">${{auction.price}}</p>
                       <!--<button class="btn btn-light col-5 pr-2">Add to cart</button>-->
                       <a class="btn btn-light col-5 pr-2" href="{% url 'indexItem' auction_id=auction.id%}">View details &raquo;</a>
                      
                    </div>
                    <br>
                </div>
            </div>
            {%endif%}
            {%endfor%}
        </div>
        
    </div>
    <br>
                              
{% endblock %}

auctions/templates/auctions/index_view.html
{% extends "auctions/layout.html" %}

{%block body%}

{% include "auctions/index-view-swiper.html" %}
<div class="container margin-bottom">

    <div class="row featurette">
        <div class="col-lg-12">
            <li style="text-align: right;">{{product.active}}</li>
            <div>
                <h2>{{product.title}} </h2><br>
            </div>

            <div>
                Description
                <p>{{product.description}}</p>
            </div>

            <div>
                Price
                <p class="col-6 ml-2">${{product.price}}</p>
            </div>

            <div>
                Seller
                <p class="col-6 ml-2">{{product.seller}}</p>
            </div>

        </div>

        <div>
            <a href="{% url 'addWatchlist' auction_id=product.id %}" class="btn btn-light col-2 pr-2">Add to
                Watchlist</a>
        </div>
    </div>

    <hr class="featurette-divider">


</div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="shortcut icon" type="image/ico" href="{% static 'favico.ico' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'auctions/background.css' %}">
        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
        
    </head>

    <body class="body">
        <header class="p-3 bg-dark text-white">
            <div class="container">
                <div div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <div>
                        {% if user.is_authenticated %}
                            Signed in as <br><strong>{{ user.username }}</strong>.
                        {% else %}
                            Not signed in.
                        {% endif %}
                    </div>
                    
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
                          </a>
                        
                            <a class="nav-link px-2 text-white" href="{% url 'index' %}">Listings</a>
                        
            
                        {% if user.is_authenticated %}
                           
                                <a class="nav-link px-2 text-white" href="{% url 'createListing' %}">Upload</a>
                           
                            
                                <a class="nav-link px-2 text-white" href="{% url 'categoryView' %}">Categories</a>
                           
                            
                                <a class="nav-link px-2 text-white" href="{% url 'watchlist' %}">Watchlist</a>
                            
                    </ul>
                                <div class="text-end">
                                    <a  style="text-align: right;" class="btn btn-warning" href="{% url 'logout' %}">Log Out</a>

                                </div>
                            
                            {% else %}
        
                            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        
                                <input type="search" class="form-control form-control-dark" placeholder="Search...">
        
                            </form>
        
                            <div >
                                <a class="btn btn-outline-light me-2" href="{% url 'login' %}">Log In</a>
                           
                                <a class="btn btn-warning" href="{% url 'register' %}">Register</a>
                            </div>
                           
                           
                        {% endif %}
            

                </div>

            </div>
        </header>
    

        <hr>

        {% block body %}
        {% endblock %}

        <footer class="bg-dark text-center text-white footer">
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.192);">
                &copy; {{ year }}
            <a class="text-white" href="http://www.westcharts.com" style="text-decoration: none;" target="_blank">westcharts.com</a>
            </div>
        </footer>
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/slider.html
{% load static %}

<head>

  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'auctions/swiper-bundle.min.css' %}">

  <!-- Demo styles -->
  <style>
    html,
    body {
      position: relative;
      height: 100%;
    }

  

    .swiper-container {
      width: 100%;
      height: 60%;
      margin-left: auto;
      margin-right: auto;
    }

    .swiper-slide {
      text-align: center;
      font-size: 18px;
      background: #fff;

      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }
  </style>
</head>


  <!-- Swiper -->
  <div class="swiper-container" style="margin-bottom: 100px;">
    <div class="swiper-wrapper">
        {% for auction in auctions %}
            <div class="swiper-slide"><img  src="{{auction.image.url}}" alt="" width = 100% ></div>
        {%endfor%}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>

  <!-- Swiper JS -->
  <script src="{% static '/auctions/scripts/swiper-bundle.js' %}"></script>

  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container', {
      slidesPerView: 1,
      spaceBetween: 30,
      loop: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
  </script>

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

{%if message%}

<div class="alert alert-success" role="alert">

    {{message}}

</div>

{% endif %}

<div class="container margin-bottom">
    <h3 style="text-align:center;">Watchlist</h3>
  {% for product in product_watchlist %}
      <div class="row featurette">
          <div class="col-md-7">
              <li style="text-align: right;">{{product.product_id.active}}</li>
              <div >
                  <h2>{{product.product_id.title}} </h2><br>
              </div>
              
              <div>
                      Description
                  <li>{{product.product_id.description}}</li>
              </div>
              <div>
                  Seller
                  <li>{{product.product_id.seller}}</li>
              </div>
              
              
            </div>
            <div class="col-md-5">
                <img src="{{product.product_id.image.url}}" alt="" width="500" height="500"> 
            </div>
            <a class="btn btn-light col-2 pr-2" href="{% url 'remove_watchlist' auction_id=product.product_id.id %}">Remove From Watchlist</a>
      </div>

      <hr class="featurette-divider">

  {%endfor%}

</div>

{% endblock %}